#!/bin/bash

###########
# This script puts symbolic links to the dotfiles into
# your home directory and sources some configuration files
# for git, etc...
###

echo "Installing Dotfiles..."

DOTFILE_DIRECTORY=$(pwd)
VIM_BUNDLE_DIRECTORY='~/.vim/bundle'
echo $DOTFILE_DIRECTORY
echo "Detecting platform..."
# Detect OS
platform='unknown'
unamestr=$(uname)

if [[ "$unamestr" == 'Linux' ]]; then
  platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
  platform='freebsd'
elif [[ "$unamestr" == 'Darwin' ]]; then
  platform='OSX'
fi

echo "Running configurations for $platform"

#Update the shit out of vim
echo "Checking Vim Version..."
if [[ $platform == 'linux' ]]; then
  read -r -p "Do you want to compile the lastest vim from scratch? [y/N] " response
  case $response in
    [yY][eE][sS]|[yY])
      sudo apt-get install libncurses5-dev libgnome2-dev libgnomeui-dev \
        libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
        libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev ruby-dev mercurial
      sudo apt-get remove vim vim-runtime gvim
      sudo apt-get remove vim-tiny vim-common vim-gui-common
      pushd ~
      hg clone https://code.google.com/p/vim/
      cd vim
      ./configure --with-features=huge \
        --enable-rubyinterp \
        --enable-pythoninterp \
        --with-python-config-dir=/usr/lib/python2.7/config \
        --enable-perlinterp \
        --enable-luainterp \
        --enable-gui=gtk2 --enable-cscope --prefix=$HOME/bin/
      make VIMRUNTIMEDIR=/usr/share/vim/vim74
      sudo make install
      ln -s $HOME/bin/bin/vim $HOME/bin/vim
      popd
      ;;
    *)
      echo "Skipping."
      ;;
  esac
fi

echo "Symlinking dotfiles to this directory..."
source ./linker.sh

rm -rf ~/.vim/colors/
mkdir -p ~/.vim/colors/
echo "Getting Pretty Colors..."
if [[ ! -f ~/.vim/colors/solarized.vim ]]; then
  curl -o ~/.vim/colors/solarized.vim https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim
fi

echo "Installing Vundle..."
mkdir -p ~/.vim/bundle/
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

echo "Running a BundleInstall for vim..."
# Run bundle install for vim
vim . +PluginInstall +qall!

# Install youcompleteme
echo "Ensuring homebrew and cmake are installed..."
if [[ $platform == 'OSX' ]]; then
  type brew >/dev/null 2>&1 || { echo >&2 "Homebrew not installed. Installing it now: "; ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"; }
  type cmake >/dev/null 2>&1 || { echo >&2 "cmake not installed. Installing it now: "; brew install cmake; }
elif [[ $platform == 'linux' ]]; then
  sudo apt-get install build-essential cmake
  sudo apt-get install python-dev
fi

echo "trying to install rbenv, then chowning ~/.rbenv/"
if [[ $platform == 'OSX' ]]; then
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
  sudo chown -R $(whoami) ~/.rbenv/
fi

echo "Setting git configs..."
# Do the git dance...
git config --global user.name "Jake Cataford"
git config --global user.email jakecataford@gmail.com
git config --global core.editor vim
git config --global help.autocorrect 1
git config --global color.ui true
git config --global core.whitespace trailing-space

echo "Sourcing bash_profile"
# And source the profile:
source ~/.bashrc
echo "🐙 🐙 🐙  Enjoy 🐙 🐙 🐙 "
